export const refs = {
  preloader: document.querySelector('.preloader'),
  movieList: document.querySelector('[data-movie-list]'),
  searchForm: document.querySelector('.search-bar'),
  movieModal: document.querySelector('[data-modal]'),
  modalCloseBtn: document.querySelector('.modal-card-close'),
  backdrop: document.querySelector('.backdrop'),
  body: document.querySelector('body'),
  authModal: document.querySelector('.auth-modal'),
  authForm: document.querySelector('.auth-form'),
  authLogin: document.querySelector('[data-auth-login]'),
  authRegister: document.querySelector('[data-auth-register]'),
  authSignOut: document.querySelector('[data-auth-sign-out]'),
  authOpen: document.querySelector('[data-auth-open]'),
  authClose: document.querySelector('[data-auth-close]'),
  pagination: document.querySelector('.pagination'),
  paginationBtns: document.querySelector('.pag-btns'),
  paginationDotsLeft: document.querySelector('.pagination-btn_dots_left'),
  paginationDotsRight: document.querySelector('.pagination-btn_dots_right'),
  paginationArrowLeft: document.querySelector('.pagination-btn_arrow_left'),
  paginationArrowRight: document.querySelector('.pagination-btn_arrow_right'),
  paginationFirst: document.querySelector('#extreme-left'),
  paginationLast: document.querySelector('#extreme-right'),
};
