import './js/Api';
import './js/refs';
import './js/auth';
import './js/home';
import './js/searchForm';
import './js/pagination';
import './js/movieModal';
import './js/authModal';
import './js/preloader';
